CREATE DATABASE IF NOT EXISTS test;
use test;
DROP TABLE IF EXISTS test_types;
CREATE TABLE test_types (
   intField   INT(6) UNSIGNED NOT NULL DEFAULT 0,
   floatField FLOAT NOT NULL DEFAULT 0,
   strField   VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB;
INSERT INTO test_types VALUES (123, 1234.5674323, '123214qwe');
GRANT ALL PRIVILEGES ON test.* TO 'test'@'%' IDENTIFIED BY 'test';
